### ISSUE TITLE
Titles in PDF

### ISSUE THREAD

**Issue by Devamitta** [sasanarakkha/sasanarakkha-recitations-book#10]
When I open PDF, generated by this software, and try to copy any name of the chant:
for example page 179 Ratanattay’ānubhā v’ādi-gātha,
it is copy with spaces after long ā : "Ratanattay’ā nubhā v’ā di-gā tha".
That's why it is not really searchable PDF.
Is it possible to avoid this? Then people can use this PDF more effectively.

**Comment by paladhammika** [comment]
I was able to search "Ratanattay’ānubhāv’ādi-gāthā" and find the title no problem.

![image](https://user-images.githubusercontent.com/93992898/160974914-fcfa0bb6-6f53-472c-860b-23d3d072ed71.png)

Though there is an issue with other titles which have characters substituted. For example, if you copy "Saraṇa-gamana-pāṭho" you'll actually get "Sara�a-gamana-pāṫho". Not sure how to go about fixing this. A simple solution is to use the sidebar ToC.

**Comment by Devamitta** [comment]
looks like it depends on software which you are using. Android Xodo Docs and Linux Xreader see the spaces after ā.
