### ISSUE TITLE
GitHub build PDF action fails since git ref is used

### ISSUE THREAD

**Issue by bergentroll** [sasanarakkha/sasanarakkha-recitations-book#14]
Last pipelines failed because PDF now depends on `.git/refs/` directory, but `.git` directory is missing for Actions.

**Comment by bergentroll** [comment]
`actions/checkout@v3` depends on `git` in `$PATH` to clone the repo in a usual way. On my way to fix.

**Comment by paladhammika** [comment]
Sādhu for the quick response though now it seems that this feature is no longer needed.

**Comment by bergentroll** [comment]
Oh, that is why I failed to find initial issue. :slightly_smiling_face: Therefore I would like to update the build image for future uses, bhante. For now there is an error of `org-tangle` with a new Emacs (v28.2).
