### ISSUE TITLE
Unnecessary files in a EPUB artifact

### ISSUE THREAD

**Issue by bergentroll** [sasanarakkha/sasanarakkha-recitations-book#17]
When opening the `SBS_Pali-English_Recitations.epub` from the releases with Sigil, it says there is a plenty redundant entries in file, which are not listed in the Manifest:
```
current-recitations.epub
source/pali-only-sandhi-split-canonical.txt
source/pali-only-sandhi-split.txt
source/pali-only-without-split.txt
source/pali-only.txt
tex/*.tex
```

The first one is also about a half of a resulting size.

If bhante like, I may exclude them in the Makefile.

**Comment by paladhammika** [comment]
Dear Bergen,

The project has been on a bit of a hiatus lately. I'm attempting to wrap it up. Would you be willing to explain what causes the the build to fail?

**Comment by bergentroll** [comment]
The reason is [zip includes any from the `manuscript/` dir](https://github.com/sasanarakkha/pali-english-recitations/blob/e34acf7ac64e387e1a70bf6924cc36ab0b741ab3/Makefile#L135). So the clear way to fix will be to move `manuscript/tex/` and other redundant for EPUB entries to another location. Other more simple way is to pass list of required files to `zip` explicitly.

:pray: :pray: :pray:

**Comment by bergentroll** [comment]
Oh, now I figured out you asked about current upload error. I will check it.

**Comment by bergentroll** [comment]
Well, there is a couple of errors.

1. Makefile trying to download `epubcheck` with `curl`, but there is no `curl` in the image. I would suggest to make downloading executable optional in the Makefile, i. e. no targets should depends on `$(EPUBCHECK)`. There is already the `epubcheck` command in the image, but it needs little fix. If you would like, I will update.

2. `make optimize` target fails because of  `No META-INF/container.xml in epub` error. Sorry, bhante, I do not know where the `container.xml` must coming from.

If building the EPUB is not crucial, it may be disabled as in [the example](https://github.com/bergentroll/sasanarakkha-build-ebooks-action/blob/d1c56dfcea966ea4ff4b5fbf9a8cb51f64c0549c/README.md?plain=1#L19) just to avoid the errors.

**Comment by bergentroll** [comment]
> There is already the `epubcheck` command in the image, but it needs little fix.

`epubcheck` shipped in the image has been fixed.

**Comment by paladhammika** [comment]
> If bhante like, I may exclude them in the Makefile.

Please do. If they aren't already. 

> So the clear way to fix will be to move manuscript/tex/ and other redundant for EPUB entries to another location.

Okay I did just that. I split up the different text formats into their own directories inside the project root.

> There is already the epubcheck command in the image, but it needs little fix. If you would like, I will update.

This has been already fixed, no?

> make optimize target fails because of No META-INF/container.xml in epub error. Sorry, bhante, I do not know where the container.xml must coming from.

This is in the epub which I was removing when using `make extractcurrent`. I've removed those lines in the make command.

**Comment by paladhammika** [comment]
I attempted to bring the 'sasanarakkha-build-actions' to the sasanarakkha organzation (https://github.com/sasanarakkha/document-build-actions).

**Comment by bergentroll** [comment]
> Please do. If they aren't already.

A resulting epub contains now only redundant `current-recitations.epub`. In the [PR21](#21)  it made ignored.

Also `epub/current-recitations.epub` as a local binary artifact should not be even presented in the repository. It seems, you already had add it to the `.gitignore`, but file is still here.

> This [`epubcheck`] has been already fixed, no?

The `Makefile` uses `assets/tools/epubcheck/`, and it is also installed `epubcheck` in the building image. The image built-in `epubcheck` had been fixed to run with `epubcheck` command, but it is not using by the Makefile for now.

It is also may not be optimal to keep exterial binary files (like `epubcheck` and `kindlegen`) in a git repository because its will be transferred and processed on every repository recieving including [CI build action](https://github.com/sasanarakkha/document-build-actions/blob/39d8fe335f5420ec3fc1cae5895e5ec9d38252b7/action.yml#L43C8-L43C8).

**Comment by paladhammika** [comment]
> It is also may not be optimal to keep exterial binary files (like `epubcheck` and `kindlegen`)

Understood. I removed `assets/tools/epubcheck/` and the redundant `current-recitations.epub`

![image](https://github.com/sasanarakkha/pali-english-recitations/assets/93992898/23f72bab-cc8e-4993-a726-e3c891237781)

**Comment by bergentroll** [comment]
`mobi` target switched to Calibre.

Also `Makefile` requisites fixed to avoid rebuilding artifacts: recurrent `make` run recreates only `*.tex` from `recitations.tex.org`. `latexmk` is a new dependency to build PDF for the same sake.

Fixed `validate` and `optimize` actions.

**Comment by bergentroll** [comment]
`mobi` target switched to Calibre.

Also `Makefile` requisites fixed to avoid rebuilding artifacts: recurrent `make` run recreates only `*.tex` from `recitations.tex.org`. `latexmk` is a new dependency to build PDF for the same sake.

Fixed `validate` and `optimize` actions.
