### ISSUE TITLE
how to use make pdf

### ISSUE THREAD

**Issue by Devamitta** [sasanarakkha/sasanarakkha-recitations-book#20]
It would be good to have a bash or at least a manual how and what to install for making work function `make pdf`

For example running in dir of repo /pali-english-recitations/:
`make pdf`
Resulting in:
Tangling org document...
/home/deva/.local/bin/org-tangle: line 2: exec: emacs: not found
make: *** [Makefile:82: pdf] Error 127

by the way function `make epub` is working well

**Comment by paladhammika** [comment]
> exec: emacs: not found

This means that a command is not found. In this case `emacs`. One can usually solve these issues by attempting to install what is `not found`. However, I found a python script which will `org-babel-tangle` all of the files without needing `emacs` installed. Please pull the latest commits and test `make pdf`.
