### ISSUE TITLE
Bhikkhuni issues

### ISSUE THREAD

**Issue by Parinibbana** [sasanarakkha/sasanarakkha-recitations-book#25]
Orig: Ekaṁsena gotami dhāreyyāsi
Change to: Ekaṁsena gotamī dhāreyyāsi 
------
Orig: Gotamī 99 you should definitely recognize
Remove endnote 99

**Comment by paladhammika** [comment]
Changed.

**Comment by paladhammika** [comment]
[gotami -> gotamī](https://github.com/sasanarakkha/pali-english-recitations/blob/ab205f72be6ac1fdb5d68d0b64991ab580dc7fe2/tex/recitations/teachings.tex#L2889)
