### ISSUE TITLE
Header formatting consistency

### ISSUE THREAD

**Issue by Parinibbana** [sasanarakkha/sasanarakkha-recitations-book#28]
The subchapter “Vowels” has a different formatting as the subchapter “Consonants”. 
Please standardize.

**Comment by paladhammika** [comment]
Bhante,

In the future, please provide screenshots.

Are you referring to the disparity in color?

![image](https://github.com/user-attachments/assets/ebe4128e-a1a0-41f1-b434-09005f7e51f6)

**Comment by Parinibbana** [comment]
It seems that both color as well as spacing are different. 
I didn't see much value of providing a screenshot, because I suspect you can find the passage quite easily by running a word search for "vowels" or "consonants".
