### ISSUE TITLE
Make commands to produce different paper sizes

### ISSUE THREAD

**Issue by paladhammika** [sasanarakkha/sasanarakkha-recitations-book#30]
Dear @bergentroll ,

I would need your help with a couple of things. 

A6 and B6 paper sizes have been introduced and so I'm wondering if there is a trivial way to produce them respectively with a make command. Something like `make pdf-a6` and `make pdf-b6`. Switching which line is commented in `/main.tex` should achieve this. 

It would also be nice if the Github actions defaults to `digitalVersion` and `afiveVersion`.

**Comment by bergentroll** [comment]
Vāndami bhante!  :pray:

Done with additional `main_*.tex` files.

- By default `bsixVersion` is set as before.
- `make pdf` makes `digitalVersion` + `afiveVersion`.
- `make pdf-a6` and `make pdf-b6` for `asixVersion` and `bsixVersion` respectively.

Please check.

**Comment by paladhammika** [comment]
That does it, thanks for your help. 

всего хорошего
